version: "3.9"

services:
  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
      - ./runtime/logs/nginx:/var/log/nginx
    ports:
      - 4201:80
    links:
      - php

  php:
    build: .docker/php
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env

  node:
    image: node:18
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
